### PR TITLE
ETW plugin to cross reference GUID with providers

### PR DESCRIPTION
**Pull request by 0xHasanM**
ETW plugin to cross reference GUID with providers

image
image

### CODE REVIEW

**Comment by EricZimmerman** [comment]
please populate at least some of the following, so the plugin can be used in batch mode:

   public string BatchValueData1 => string.Empty;
        public string BatchValueData2 => string.Empty;
        public string BatchValueData3 => string.Empty;

see other plugins for examples

**Comment by EricZimmerman** [comment]
where did this come from?

using (var reader = new StreamReader(@".\Settings\ETW.csv"))

what generates that file? 

what if the file is not there?

why do you need to do this?

**Comment by 0xHasanM** [comment]
> where did this come from?
> 
> using (var reader = new StreamReader(@".\Settings\ETW.csv"))
> 
> what generates that file?
> 
> what if the file is not there?
> 
> why do you need to do this?

This file contains the GUID and its providers. Sorry forgot to upload it too.

image

Maybe you have a better way to implement it in mind?

**Comment by EricZimmerman** [comment]
Why tho. I don't understand why you wouldn't just do a PR against my existing list of 1000+ guids vs tracking dupes potentially

**Comment by 0xHasanM** [comment]
Created a pull request to GUIDMapping. I will pull it once you push it to NuGet.

**Comment by EricZimmerman** [comment]
Guid mapping 1.1.2.0 pushed

**Comment by 0xHasanM** [comment]
Added GuidMapping instead of CSV and populated batch values.

**Pull request merged**
