### PR TITLE
Update the UserAssist plugin, so analysts won't need to go through every key.

### PR DESCRIPTION
**Pull request by 0xHasanM**
Added for loop to plugin code, so it loops over all keys under UserAssist key like USB & USBStor plugins and presents the data instead of going through all keys one by one under UserAssist.

UserAssist

### CODE REVIEW

**Comment by AndrewRathbun** [comment]
@EricZimmerman this one is all you. Right after you recompiled all the plugins 😋

**Comment by 0xHasanM** [comment]
Done : )

Animation

**Comment by EricZimmerman** [comment]
plugin is live

**Comment by 0xHasanM** [comment]
Thanks a lot. I will be glad if there is anything else I can help with.

**Comment by AndrewRathbun** [comment]
> Thanks a lot. I will be glad if there is anything else I can help with.

If you're looking for more to do, hit me up on the Digital Forensics Discord Server.

**Comment by 0xHasanM** [comment]
> > Thanks a lot. I will be glad if there is anything else I can help with.
> 
> If you're looking for more to do, hit me up on the Digital Forensics Discord Server.

Done 😄

**Pull request merged**
