### PR TITLE
Update TODO

### PR DESCRIPTION
**Pull request by hyuunnn**
https://github.com/EricZimmerman/RegistryPlugins/blob/master/RegistryPlugin.AppCompatFlags2

### CODE REVIEW

**Comment by rathbuna** [comment]
Thank you for your work. I'm guessing Installed Apps is the Uninstall key?

**Comment by hyuunnn** [comment]
@rathbuna Maybe.

**Comment by rathbuna** [comment]
@hyuunnn once this gets merged, I will compile a list of what else needs to be done. I'll likely just be pulling from big wins from the Kroll Batch file that could use a plugin, within reason.

**Comment by rathbuna** [comment]
@EricZimmerman this is ready to merge whenever. Simple TODO update.

**Pull request merged**
