### PR TITLE
Add .net5 support

### PR DESCRIPTION
**Pull request by cohennadi**
Add .net5 support to UserAssist, and Bam

### CODE REVIEW

**Comment by EricZimmerman** [comment]
can you do the entire project, including the interfaces?

**Comment by cohennadi** [comment]
I converted 44 projects, the last projects remaining have dependency issues: 
Services and Test.
I could not make it work, and I would glad if you could merge this pull request and do the remains projects in another time.

**Comment by agoodhockey** [comment]
Any progress on this?

**Comment by EricZimmerman** [comment]
merged it just now

**Comment by cohennadi** [comment]
Thanks!

**Pull request merged**
